In [63]:
import pandas as pd

movies = pd.read_csv("../data/movies_metadata.csv")
keywords = pd.read_csv("../data/keywords.csv")
credits = pd.read_csv("../data/credits.csv")

C:\Users\anuma\AppData\Local\Temp\ipykernel_26196\2468237679.py:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  movies = pd.read_csv("../data/movies_metadata.csv")

In [64]:
movies.head(1)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0

In [65]:
keywords.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [66]:
credits.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [67]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [68]:
keywords.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46419 entries, 0 to 46418
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        46419 non-null  int64
 1   keywords  46419 non-null  object
dtypes: int64(1), object(1)
memory usage: 725.4+ KB

In [69]:
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45476 entries, 0 to 45475
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   cast    45476 non-null  object
 1   crew    45476 non-null  object
 2   id      45476 non-null  int64
dtypes: int64(1), object(2)
memory usage: 1.0+ MB

In [70]:
print(f"Keywords Null values before: {keywords.isnull().sum().sum()}")
keywords.dropna(inplace = True)
print(f"Keywords Null values after: {keywords.isnull().sum().sum()}")

Keywords Null values before: 0
Keywords Null values after: 0

In [71]:
print(f"Credits Null values before: {credits.isnull().sum().sum()}")
credits.dropna(inplace = True)
print(f"Credits Null values after: {credits.isnull().sum().sum()}")

Credits Null values before: 0
Credits Null values after: 0

In [72]:
additional_data = keywords.merge(credits, on='id')
additional_data.head()

,id,keywords,cast,crew
0,862,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,8844,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,15602,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."
3,31357,"[{'id': 818, 'name': 'based on novel'}, {'id':...","[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de..."
4,11862,"[{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...","[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de..."

In [75]:
columns_to_drop = ['adult', 'belongs_to_collection', 'budget', 'homepage', 'imdb_id', 'runtime', 'tagline', 'popularity', 'poster_path', 'revenue', 'vote_average', 'vote_count', 'video', 'original_language']

df = movies.drop(columns=columns_to_drop, axis = 1)
df.head(2)

,genres,id,original_title,overview,production_companies,production_countries,release_date,spoken_languages,status,title
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Toy Story
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Jumanji

In [77]:
ids_to_delete = []
for id in df['id']:
    try:
        int_id = int(id)
        # file.write(f"{int_id}\n")
    except:
        ids_to_delete.append(id)
        
df = df[~df['id'].isin(ids_to_delete)]
df.reset_index(drop=True, inplace=True)

In [78]:
df['id'] = df['id'].astype(int)
additional_data['id'] = additional_data['id'].astype(int)

final_df = df.merge(additional_data, on='id')
final_df.head(3)

C:\Users\anuma\AppData\Local\Temp\ipykernel_26196\1990758321.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['id'] = df['id'].astype(int)

,genres,id,original_title,overview,production_companies,production_countries,release_date,spoken_languages,status,title,keywords,cast,crew
0,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",862,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-10-30,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Toy Story,"[{'id': 931, 'name': 'jealousy'}, {'id': 4290,...","[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de..."
1,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",8844,Jumanji,When siblings Judy and Peter discover an encha...,"[{'name': 'TriStar Pictures', 'id': 559}, {'na...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-15,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Jumanji,"[{'id': 10090, 'name': 'board game'}, {'id': 1...","[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de..."
2,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",15602,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'name': 'Warner Bros.', 'id': 6194}, {'name'...","[{'iso_3166_1': 'US', 'name': 'United States o...",1995-12-22,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Grumpier Old Men,"[{'id': 1495, 'name': 'fishing'}, {'id': 12392...","[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de..."

In [79]:
def extract_data(data_dict):
    import ast
    if not isinstance(data_dict, str):
        return []
    data_list = ast.literal_eval(data_dict)
    data_list = ["".join(data['name'].split()) for data in data_list]
    return data_list

def extract_director_and_producer(crew_data):
    import ast
    if not isinstance(crew_data, str):
        return []
    crew_list = ast.literal_eval(crew_data)
    directors = ["".join(member['name'].split()) for member in crew_list if member['job'] == 'Director']
    producers = ["".join(member['name'].split()) for member in crew_list if member['job'] == 'Producer']
    directors.extend(producers)
    return directors

final_df['genres'] = final_df['genres'].apply(extract_data)
final_df['production_companies'] = final_df['production_companies'].apply(extract_data)
final_df['production_countries'] = final_df['production_countries'].apply(extract_data)
final_df['spoken_languages'] = final_df['spoken_languages'].apply(extract_data)
final_df['keywords'] = final_df['keywords'].apply(extract_data)
final_df['cast'] = final_df['cast'].apply(extract_data)
final_df['crew'] = final_df['crew'].apply(extract_director_and_producer)
final_df['overview'] = final_df['overview'].apply(lambda x: x.split() if isinstance(x, str) else [])

In [80]:
print(final_df.shape)
final_df.head(1)

(46628, 13)

,genres,id,original_title,overview,production_companies,production_countries,release_date,spoken_languages,status,title,keywords,cast,crew
0,"[Animation, Comedy, Family]",862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...",[PixarAnimationStudios],[UnitedStatesofAmerica],1995-10-30,[English],Released,Toy Story,"[jealousy, toy, boy, friendship, friends, riva...","[TomHanks, TimAllen, DonRickles, JimVarney, Wa...","[JohnLasseter, BonnieArnold, RalphGuggenheim]"

In [56]:
final_df['all_tags'] = final_df['overview'] + final_df['genres'] + final_df['production_companies'] + final_df['production_countries'] + final_df['spoken_languages'] + final_df['original_language'] + final_df['keywords'] + final_df['cast'] + final_df['crew']
final_df = final_df[['id', 'title', 'all_tags', 'release_date']]
final_df.head()

,id,title,all_tags,release_date
0,862,Toy Story,"[Led, by, Woody,, Andy's, toys, live, happily,...",1995-10-30
1,8844,Jumanji,"[When, siblings, Judy, and, Peter, discover, a...",1995-12-15
2,15602,Grumpier Old Men,"[A, family, wedding, reignites, the, ancient, ...",1995-12-22
3,31357,Waiting to Exhale,"[Cheated, on,, mistreated, and, stepped, on,, ...",1995-12-22
4,11862,Father of the Bride Part II,"[Just, when, George, Banks, has, recovered, fr...",1995-02-10

In [57]:
import re
from nltk.stem import SnowballStemmer

snow_stemmer = SnowballStemmer(language='english', ignore_stopwords=True)

def clean_tags(tags):
    cleaned = []
    for tag in tags:
        tag = tag.lower()
        tag = re.sub(r'[^a-z0-9\s]', '', tag)
        tag = re.sub(r'\s+', ' ', tag).strip()
        tag = snow_stemmer.stem(tag)
        if tag:
            cleaned.append(tag)
    return " ".join(cleaned)

final_df['all_tags'] = final_df['all_tags'].apply(clean_tags)
final_df.head()

,id,title,all_tags,release_date
0,862,Toy Story,led by woodi andi toy live happili in his room...,1995-10-30
1,8844,Jumanji,when sibl judi and peter discov an enchant boa...,1995-12-15
2,15602,Grumpier Old Men,a famili wed reignit the ancient feud between ...,1995-12-22
3,31357,Waiting to Exhale,cheat on mistreat and step on the women are ho...,1995-12-22
4,11862,Father of the Bride Part II,just when georg bank has recov from his daught...,1995-02-10

In [58]:
print("Nulls before:\n", final_df.isnull().sum())
final_df.dropna(inplace=True)
print("Nulls after:\n", final_df.isnull().sum())

print("Duplicates before:", final_df.duplicated().sum())
final_df.drop_duplicates(inplace=True)
print("Duplicates after:", final_df.duplicated().sum())

Nulls before:
 id               0
title            4
all_tags         0
release_date    88
dtype: int64
Nulls after:
 id              0
title           0
all_tags        0
release_date    0
dtype: int64
Duplicates before: 1192
Duplicates after: 0

In [59]:
final_df.head()

,id,title,all_tags,release_date
0,862,Toy Story,led by woodi andi toy live happili in his room...,1995-10-30
1,8844,Jumanji,when sibl judi and peter discov an enchant boa...,1995-12-15
2,15602,Grumpier Old Men,a famili wed reignit the ancient feud between ...,1995-12-22
3,31357,Waiting to Exhale,cheat on mistreat and step on the women are ho...,1995-12-22
4,11862,Father of the Bride Part II,just when georg bank has recov from his daught...,1995-02-10

In [60]:
final_df['release_date'] = final_df['release_date'].astype('object')

final_df['year'] = final_df['release_date'].apply(lambda x : x[:4]).astype(int)

final_df = final_df[final_df['year'] >= 1975]
final_df.sort_values(by = 'year')
final_df.head()

,id,title,all_tags,release_date,year
0,862,Toy Story,led by woodi andi toy live happili in his room...,1995-10-30,1995
1,8844,Jumanji,when sibl judi and peter discov an enchant boa...,1995-12-15,1995
2,15602,Grumpier Old Men,a famili wed reignit the ancient feud between ...,1995-12-22,1995
3,31357,Waiting to Exhale,cheat on mistreat and step on the women are ho...,1995-12-22,1995
4,11862,Father of the Bride Part II,just when georg bank has recov from his daught...,1995-02-10,1995

In [62]:
final_df['all_tags'][0]

'led by woodi andi toy live happili in his room until andi birthday bring buzz lightyear onto the scene afraid of lose his place in andi heart woodi plot against buzz but when circumst separ buzz and woodi from their owner the duo eventu learn to put asid their differ anim comedi famili pixaranimationstudio unitedstatesofamerica english jealousi toy boy friendship friend rivalri boynextdoor newtoy toycomestolif tomhank timallen donrickl jimvarney wallaceshawn johnratzenberg anniepott johnmorri erikvondetten lauriemetcalf rleeermey sarahfreeman pennjillett johnlasset bonniearnold ralphguggenheim'