In [58]:
import pandas as pd

movies = pd.read_csv("../data/TMDB_movie_dataset_v11.csv")

In [59]:
movies.head(1)

,id,title,vote_average,vote_count,status,release_date,revenue,runtime,adult,backdrop_path,...,original_title,overview,popularity,poster_path,tagline,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,8.364,34495,Released,2010-07-15,825532764,148,False,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,...,Inception,"Cobb, a skilled thief who commits corporate es...",83.952,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,Your mind is the scene of the crime.,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."

In [60]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1355359 entries, 0 to 1355358
Data columns (total 24 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   id                    1355359 non-null  int64
 1   title                 1355341 non-null  object
 2   vote_average          1355359 non-null  float64
 3   vote_count            1355359 non-null  int64
 4   status                1355359 non-null  object
 5   release_date          1071468 non-null  object
 6   revenue               1355359 non-null  int64
 7   runtime               1355359 non-null  int64
 8   adult                 1355359 non-null  bool
 9   backdrop_path         341609 non-null   object
 10  budget                1355359 non-null  int64
 11  homepage              140158 non-null   object
 12  imdb_id               653468 non-null   object
 13  original_language     1355359 non-null  object
 14  original_title        1355341 non-null  object
 15  overview              1049721 non-null  object
 16  popularity            1355359 non-null  float64
 17  poster_path           886047 non-null   object
 18  tagline               188619 non-null   object
 19  genres                769970 non-null   object
 20  production_companies  584531 non-null   object
 21  production_countries  710843 non-null   object
 22  spoken_languages      735888 non-null   object
 23  keywords              341045 non-null   object
dtypes: bool(1), float64(2), int64(5), object(16)
memory usage: 239.1+ MB

In [61]:
movies.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'adult', 'backdrop_path', 'budget', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'keywords'],
      dtype='object')

In [62]:
columns_to_drop = ['adult', 'budget', 'backdrop_path', 'homepage', 'imdb_id', 'runtime', 'tagline', 'popularity', 'revenue', 'vote_average', 'vote_count', 'original_language']

df = movies.drop(columns=columns_to_drop, axis = 1)
df.head(1)

,id,title,status,release_date,original_title,overview,poster_path,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,Released,2010-07-15,Inception,"Cobb, a skilled thief who commits corporate es...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,"Action, Science Fiction, Adventure","Legendary Pictures, Syncopy, Warner Bros. Pict...","United Kingdom, United States of America","English, French, Japanese, Swahili","rescue, mission, dream, airplane, paris, franc..."

In [63]:
df.isnull().sum()

id                            0
title                        18
status                        0
release_date             283891
original_title               18
overview                 305638
poster_path              469312
genres                   585389
production_companies     770828
production_countries     644516
spoken_languages         619471
keywords                1014314
dtype: int64

In [64]:
df.duplicated().sum()

np.int64(441)

In [65]:
df.dropna(subset = 'title', inplace = True)
df.drop_duplicates(subset = 'title', inplace = True)
df.dropna(subset = 'overview', inplace = True)
df.drop_duplicates(subset = 'overview', inplace = True)
df.dropna(subset = 'poster_path', inplace = True)
df.drop_duplicates(subset = 'poster_path', inplace = True)
df.dropna(subset = 'release_date', inplace = True)

In [66]:
df.isnull().sum()

id                           0
title                        0
status                       0
release_date                 0
original_title               0
overview                     0
poster_path                  0
genres                  164703
production_companies    226986
production_countries    179142
spoken_languages        160305
keywords                349179
dtype: int64

In [67]:
df.shape

(560524, 12)

In [68]:
df['genres'] = df['genres'].apply(lambda x : str(x).split(','))
df['production_companies'] = df['production_companies'].apply(lambda x : str(x).split(','))
df['production_countries'] = df['production_countries'].apply(lambda x : str(x).split(','))
df['spoken_languages'] = df['spoken_languages'].apply(lambda x : str(x).split(','))
df['keywords'] = df['keywords'].apply(lambda x : str(x).split(','))
df['overview'] = df['overview'].apply(lambda x: str(x).split())

df.head(1)

,id,title,status,release_date,original_title,overview,poster_path,genres,production_companies,production_countries,spoken_languages,keywords
0,27205,Inception,Released,2010-07-15,Inception,"[Cobb,, a, skilled, thief, who, commits, corpo...",/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,"[Action, Science Fiction, Adventure]","[Legendary Pictures, Syncopy, Warner Bros. P...","[United Kingdom, United States of America]","[English, French, Japanese, Swahili]","[rescue, mission, dream, airplane, paris, ..."

In [69]:
df['all_tags'] = df['overview'] + df['genres'] + df['production_companies'] + df['production_countries'] + df['spoken_languages'] + df['keywords']
df = df[['id', 'title', 'poster_path', 'all_tags', 'release_date', 'status']]
df.head()

,id,title,poster_path,all_tags,release_date,status
0,27205,Inception,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,"[Cobb,, a, skilled, thief, who, commits, corpo...",2010-07-15,Released
1,157336,Interstellar,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,"[The, adventures, of, a, group, of, explorers,...",2014-11-05,Released
2,155,The Dark Knight,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,"[Batman, raises, the, stakes, in, his, war, on...",2008-07-16,Released
3,19995,Avatar,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,"[In, the, 22nd, century,, a, paraplegic, Marin...",2009-12-15,Released
4,24428,The Avengers,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,"[When, an, unexpected, enemy, emerges, and, th...",2012-04-25,Released

In [70]:
import re
from nltk.stem import WordNetLemmatizer

import nltk
nltk.download('wordnet')

ss = WordNetLemmatizer()

def clean_tags(tags):
    cleaned = []
    if not isinstance(tags, list):
        return None
    for tag in tags:
        tag = tag.lower()
        tag = re.sub(r'[^a-z0-9\s]', '', tag)
        tag = re.sub(r'\s+', ' ', tag).strip()
        tag = ss.lemmatize(tag)
        if tag:
            cleaned.append(tag)
    return " ".join(cleaned)

df['all_tags'] = df['all_tags'].apply(clean_tags)
df.head()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\acer\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

,id,title,poster_path,all_tags,release_date,status
0,27205,Inception,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,cobb a skilled thief who commits corporate esp...,2010-07-15,Released
1,157336,Interstellar,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,the adventure of a group of explorer who make ...,2014-11-05,Released
2,155,The Dark Knight,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,batman raise the stake in his war on crime wit...,2008-07-16,Released
3,19995,Avatar,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,in the 22nd century a paraplegic marine is dis...,2009-12-15,Released
4,24428,The Avengers,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,when an unexpected enemy emerges and threatens...,2012-04-25,Released

In [73]:
df['release_date'] = df['release_date'].astype('object')

df['year'] = df['release_date'].apply(lambda x : x[:4]).astype(int)

df = df[df['year'] >= 1975]
df.sort_values(by = 'year')

df = df[(df['status'] != 'Rumored') | (df['status'] != 'Canceled') & (df['status'] != 'Planned')]

print(df.shape)
df.head()

(485101, 7)

,id,title,poster_path,all_tags,release_date,status,year
0,27205,Inception,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,cobb a skilled thief who commits corporate esp...,2010-07-15,Released,2010
1,157336,Interstellar,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,the adventure of a group of explorer who make ...,2014-11-05,Released,2014
2,155,The Dark Knight,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,batman raise the stake in his war on crime wit...,2008-07-16,Released,2008
3,19995,Avatar,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,in the 22nd century a paraplegic marine is dis...,2009-12-15,Released,2009
4,24428,The Avengers,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,when an unexpected enemy emerges and threatens...,2012-04-25,Released,2012

In [74]:
df['status'].value_counts()

status
Released           478946
In Production        3983
Post Production      1552
Planned               603
Rumored                12
Canceled                5
Name: count, dtype: int64